import argparse
import json
import os
from datetime import datetime

from fetcher import NewsItem, fetch_stock_news
from file_handler import save_to_file
from insights import generate_ai_insights, load_openai_key
from publisher import publish_to_webhook


DEFAULT_CONFIG = {
    "feeds": [
        "https://news.google.com/rss/search?q=stock%20market&hl=en-US&gl=US&ceid=US:en",
        "https://news.google.com/rss/search?q=S%26P%20500%20OR%20NASDAQ&hl=en-US&gl=US&ceid=US:en",
        "https://news.google.com/rss/search?q=earnings%20report%20stocks&hl=en-US&gl=US&ceid=US:en",
    ],
    "max_items": 8,
    "output_dir": "posts",
    "webhook_url_env": "NEWS_WEBHOOK_URL",
    "insights_enabled": True,
    "insights_max_points": 4,
    "openai_api_key_env": "OPENAI_API_KEY",
    "openai_model": "gpt-4.1-mini",
}


def load_config(config_path: str) -> dict:
    if not os.path.exists(config_path):
        with open(config_path, "w", encoding="utf-8") as file:
            json.dump(DEFAULT_CONFIG, file, indent=2)
        print(f"Created default config at {config_path}")
        return DEFAULT_CONFIG

    with open(config_path, "r", encoding="utf-8") as file:
        user_config = json.load(file)

    config = DEFAULT_CONFIG.copy()
    config.update(user_config)
    return config


def _short(text: str, max_len: int = 160) -> str:
    clean = " ".join((text or "").split())
    if len(clean) <= max_len:
        return clean
    return clean[: max_len - 3].rstrip() + "..."


def build_daily_post(items: list[NewsItem], now: datetime, insights: list[str] | None = None) -> str:
    if not items:
        return f"Daily Stock News - {now:%Y-%m-%d}\n\nNo news items were found today."

    lines = [f"Daily Stock News - {now:%Y-%m-%d}", ""]
    if insights:
        lines.append("AI Insights")
        for point in insights:
            lines.append(f"- {point}")
        lines.append("")

    for idx, item in enumerate(items, start=1):
        lines.append(f"{idx}. {item.title}")
        lines.append(f"   Source: {item.source}")
        if item.summary:
            lines.append(f"   Summary: {_short(item.summary)}")
        lines.append(f"   Link: {item.link}")
        lines.append("")

    lines.append("Auto-generated by your stock news AI agent.")
    return "\n".join(lines)


def agent_run(config_path: str, publish: bool) -> None:
    print("Agent started...")

    config = load_config(config_path)
    items = fetch_stock_news(
        feeds=config["feeds"],
        max_items=int(config.get("max_items", 8)),
    )

    now = datetime.now()
    insights: list[str] = []
    if bool(config.get("insights_enabled", True)):
        openai_key_env = config.get("openai_api_key_env", "OPENAI_API_KEY")
        openai_key = load_openai_key(openai_key_env)
        insights = generate_ai_insights(
            items=items,
            api_key=openai_key,
            model=config.get("openai_model", "gpt-4.1-mini"),
            max_points=int(config.get("insights_max_points", 4)),
        )
    post_text = build_daily_post(items, now, insights=insights)
    saved_path = save_to_file(post_text, output_dir=config.get("output_dir", "posts"), prefix="stock_news")

    if not saved_path:
        print("No post saved.")
        return

    if publish:
        webhook_env_name = config.get("webhook_url_env", "NEWS_WEBHOOK_URL")
        webhook_url = os.getenv(webhook_env_name, "")
        if not webhook_url:
            print(f"Publish skipped: set environment variable '{webhook_env_name}' with your webhook URL.")
            return

        success = publish_to_webhook(webhook_url, post_text)
        print("Webhook publish: success" if success else "Webhook publish: failed")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Daily stock news agent")
    parser.add_argument("--config", default="agent_config.json", help="Path to config JSON")
    parser.add_argument("--publish", action="store_true", help="Post to webhook in addition to saving a file")
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    agent_run(config_path=args.config, publish=args.publish)
