import argparse
import base64
import json
import os
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

from fetcher import NewsItem, fetch_stock_news
from file_handler import save_to_file
from insights import generate_ai_insights, load_openai_key
from publisher import publish_to_webhook


DEFAULT_CONFIG = {
    "feeds": [
        "https://news.google.com/rss/search?q=stock%20market&hl=en-US&gl=US&ceid=US:en",
        "https://news.google.com/rss/search?q=S%26P%20500%20OR%20NASDAQ&hl=en-US&gl=US&ceid=US:en",
        "https://news.google.com/rss/search?q=earnings%20report%20stocks&hl=en-US&gl=US&ceid=US:en",
    ],
    "max_items": 8,
    "output_dir": "posts",
    "webhook_url_env": "NEWS_WEBHOOK_URL",
    "insights_enabled": True,
    "insights_max_points": 4,
    "openai_api_key_env": "GROQ_API_KEY",
    "openai_model": "llama-3.3-70b-versatile",
    "report_email": "pranayshah465@gmail.com",
}


def load_config(config_path: str) -> dict:
    if not os.path.exists(config_path):
        with open(config_path, "w", encoding="utf-8") as file:
            json.dump(DEFAULT_CONFIG, file, indent=2)
        print(f"Created default config at {config_path}")
        return DEFAULT_CONFIG

    with open(config_path, "r", encoding="utf-8") as file:
        user_config = json.load(file)

    config = DEFAULT_CONFIG.copy()
    config.update(user_config)
    return config


def _short(text: str, max_len: int = 160) -> str:
    clean = " ".join((text or "").split())
    if len(clean) <= max_len:
        return clean
    return clean[: max_len - 3].rstrip() + "..."


def build_daily_post(items: list[NewsItem], now: datetime, insights: list[str] | None = None) -> str:
    if not items:
        return f"Daily Stock News - {now:%Y-%m-%d}\n\nNo news items were found today."

    lines = [f"Daily Stock News - {now:%Y-%m-%d}", ""]
    if insights:
        lines.append("AI Insights")
        for point in insights:
            lines.append(f"- {point}")
        lines.append("")

    for idx, item in enumerate(items, start=1):
        lines.append(f"{idx}. {item.title}")
        lines.append(f"   Source: {item.source}")
        if item.summary:
            lines.append(f"   Summary: {_short(item.summary)}")
        lines.append(f"   Link: {item.link}")
        lines.append("")

    lines.append("Auto-generated by your stock news AI agent.")
    return "\n".join(lines)


def get_gmail_service():
    creds = Credentials(
        token=None,
        refresh_token=os.environ['GOOGLE_REFRESH_TOKEN'],
        token_uri='https://oauth2.googleapis.com/token',
        client_id=os.environ['GOOGLE_CLIENT_ID'],
        client_secret=os.environ['GOOGLE_CLIENT_SECRET'],
        scopes=['https://www.googleapis.com/auth/gmail.modify'],
    )
    creds.refresh(Request())
    return build('gmail', 'v1', credentials=creds)


def send_email_report(items: list[NewsItem], insights: list[str], now: datetime, to_email: str):
    if not to_email:
        return

    insight_rows = ''.join(f'<li>{i}</li>' for i in insights) if insights else '<li>No AI insights available.</li>'
    news_rows = ''.join(
        f'''<tr>
              <td style="padding:10px 14px;border-bottom:1px solid #eee">
                <a href="{item.link}" style="color:#1a73e8;font-weight:bold;text-decoration:none">{item.title}</a><br>
                <span style="color:#888;font-size:12px">{item.source}</span>
              </td>
            </tr>'''
        for item in items
    )

    html = f"""
<html><body style="font-family:Arial,sans-serif;color:#222;max-width:650px;margin:auto">
<h2 style="background:#0f9d58;color:#fff;padding:14px 20px;border-radius:6px;margin:0">
  Daily Stock News — {now:%A, %d %B %Y}
</h2>

<h3 style="color:#0f9d58;margin-top:20px">AI Insights</h3>
<ul style="line-height:1.8">{insight_rows}</ul>

<h3 style="color:#0f9d58;margin-top:20px">Top Headlines</h3>
<table style="width:100%;border-collapse:collapse;font-size:14px">
  {news_rows}
</table>

<p style="margin-top:24px;color:#666;font-size:12px">
  Auto-generated by your Stock News AI Agent &bull; {now:%Y-%m-%d %H:%M}
</p>
</body></html>
"""

    try:
        service = get_gmail_service()
        msg = MIMEMultipart('alternative')
        msg['Subject'] = f'Stock News Report — {now:%d %b %Y} — {len(items)} stories'
        msg['From'] = 'me'
        msg['To'] = to_email
        msg.attach(MIMEText(html, 'html'))
        raw = base64.urlsafe_b64encode(msg.as_bytes()).decode()
        service.users().messages().send(userId='me', body={'raw': raw}).execute()
        print(f"Report emailed to {to_email}")
    except Exception as e:
        print(f"Email report failed: {e}")


def agent_run(config_path: str, publish: bool) -> None:
    print("Agent started...")

    config = load_config(config_path)
    items = fetch_stock_news(
        feeds=config["feeds"],
        max_items=int(config.get("max_items", 8)),
    )

    now = datetime.now()
    insights: list[str] = []
    if bool(config.get("insights_enabled", True)):
        openai_key_env = config.get("openai_api_key_env", "GROQ_API_KEY")
        openai_key = load_openai_key(openai_key_env)
        insights = generate_ai_insights(
            items=items,
            api_key=openai_key,
            model=config.get("openai_model", "llama-3.3-70b-versatile"),
            max_points=int(config.get("insights_max_points", 4)),
        )

    post_text = build_daily_post(items, now, insights=insights)
    saved_path = save_to_file(post_text, output_dir=config.get("output_dir", "posts"), prefix="stock_news")

    if not saved_path:
        print("No post saved.")
        return

    # Send email report
    report_email = config.get("report_email", "") or os.getenv("REPORT_EMAIL", "")
    send_email_report(items, insights, now, report_email)

    if publish:
        webhook_env_name = config.get("webhook_url_env", "NEWS_WEBHOOK_URL")
        webhook_url = os.getenv(webhook_env_name, "")
        if not webhook_url:
            print(f"Publish skipped: set '{webhook_env_name}' env var to enable webhook.")
            return
        success = publish_to_webhook(webhook_url, post_text)
        print("Webhook publish: success" if success else "Webhook publish: failed")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Daily stock news agent")
    parser.add_argument("--config", default="agent_config.json", help="Path to config JSON")
    parser.add_argument("--publish", action="store_true", help="Post to webhook in addition to saving a file")
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    agent_run(config_path=args.config, publish=args.publish)
