import argparse
import base64
import json
import os
import time
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

from delivery_data import TodayDeliverySnapshot, TodayDeliveryStock, build_sector_top, fetch_today_delivery_top
from fetcher import NewsItem, fetch_stock_news
from file_handler import save_to_file
from insights import generate_ai_insights, load_openai_key
from publisher import publish_to_webhook


DEFAULT_CONFIG = {
    "feeds": [
        "https://news.google.com/rss/search?q=Indian%20stock%20market%20Nifty%20Sensex&hl=en-IN&gl=IN&ceid=IN:en",
        "https://news.google.com/rss/search?q=NSE%20BSE%20stocks%20India%20earnings&hl=en-IN&gl=IN&ceid=IN:en",
        "https://news.google.com/rss/search?q=Indian%20equity%20market%20sector%20stocks&hl=en-IN&gl=IN&ceid=IN:en",
    ],
    "max_items": 10,
    "output_dir": "posts",
    "webhook_url_env": "NEWS_WEBHOOK_URL",
    "insights_enabled": True,
    "insights_max_points": 4,
    "openai_api_key_env": "GROQ_API_KEY",
    "openai_model": "llama-3.3-70b-versatile",
    "report_email": "pranayshah465@gmail.com",
    "delivery_enabled": True,
    "delivery_trading_days": 5,
    "delivery_top_per_sector": 5,
    "delivery_min_total_traded_qty": 50000,
}


def load_config(config_path: str) -> dict:
    if not os.path.exists(config_path):
        with open(config_path, "w", encoding="utf-8") as file:
            json.dump(DEFAULT_CONFIG, file, indent=2)
        print(f"Created default config at {config_path}")
        return DEFAULT_CONFIG

    with open(config_path, "r", encoding="utf-8") as file:
        user_config = json.load(file)

    config = DEFAULT_CONFIG.copy()
    config.update(user_config)
    return config


def _short(text: str, max_len: int = 160) -> str:
    clean = " ".join((text or "").split())
    if len(clean) <= max_len:
        return clean
    return clean[: max_len - 3].rstrip() + "..."


def _format_qty(value: int) -> str:
    return f"{value:,}"


def build_delivery_lines(snapshot: TodayDeliverySnapshot | None) -> list[str]:
    lines: list[str] = ["Top Delivery % Stocks — Today (Highest to Lowest)", ""]
    if not snapshot or not snapshot.has_data:
        lines.append("NSE delivery data was unavailable for this run.")
        if snapshot and snapshot.errors:
            lines.append(f"Note: {snapshot.errors[-1]}")
        lines.append("")
        return lines

    lines.append(f"Trade date: {snapshot.trade_date:%d %b %Y}")
    lines.append("")
    for idx, s in enumerate(snapshot.stocks, start=1):
        lines.append(
            f"{idx:>2}. {s.symbol:<15} {s.delivery_percent:>5.1f}%   "
            f"Close: ₹{s.close_price:.2f}   Delivery Qty: {_format_qty(s.delivery_qty)}"
        )
    lines.append("")
    return lines


def build_daily_post(
    items: list[NewsItem],
    now: datetime,
    insights: list[str] | None = None,
    delivery_snapshot: TodayDeliverySnapshot | None = None,
) -> str:
    lines = [f"Indian Stock Market Report - {now:%Y-%m-%d}", ""]
    if insights:
        lines.append("Coming Week Sector Outlook")
        for point in insights:
            lines.append(f"- {point}")
        lines.append("")

    lines.extend(build_delivery_lines(delivery_snapshot))

    if not items:
        lines.append("Indian Market Headlines")
        lines.append("")
        lines.append("No Indian stock market news items were found today.")
        return "\n".join(lines)

    lines.append("Indian Market Headlines")
    lines.append("")
    for idx, item in enumerate(items, start=1):
        lines.append(f"{idx}. {item.title}")
        lines.append(f"   Source: {item.source}")
        if item.summary:
            lines.append(f"   Summary: {_short(item.summary)}")
        lines.append(f"   Link: {item.link}")
        lines.append("")

    lines.append("Auto-generated by your Indian stock market AI agent.")
    return "\n".join(lines)


def get_gmail_service():
    creds = Credentials(
        token=None,
        refresh_token=os.environ['GOOGLE_REFRESH_TOKEN'],
        token_uri='https://oauth2.googleapis.com/token',
        client_id=os.environ['GOOGLE_CLIENT_ID'],
        client_secret=os.environ['GOOGLE_CLIENT_SECRET'],
        scopes=['https://www.googleapis.com/auth/gmail.modify'],
    )
    creds.refresh(Request())
    return build('gmail', 'v1', credentials=creds)


def _is_gmail_rate_limit(exc: Exception) -> bool:
    if not isinstance(exc, HttpError):
        return False
    status = getattr(exc.resp, "status", None)
    return status in (403, 429) and "ratelimit" in str(exc).lower()


def send_gmail_message_with_retries(service, raw: str) -> None:
    for attempt, wait_seconds in enumerate([0, 30, 60, 120], start=1):
        if wait_seconds:
            print(f"Gmail rate limit hit. Retrying email report in {wait_seconds}s...")
            time.sleep(wait_seconds)
        try:
            service.users().messages().send(userId='me', body={'raw': raw}).execute()
            return
        except Exception as exc:
            if attempt < 4 and _is_gmail_rate_limit(exc):
                continue
            raise


def build_delivery_html(snapshot: TodayDeliverySnapshot | None) -> str:
    if not snapshot or not snapshot.has_data:
        note = "NSE delivery data was unavailable for this run."
        if snapshot and snapshot.errors:
            note += f" Note: {snapshot.errors[-1]}"
        return f'<p style="color:#666">{note}</p>'

    rows = "".join(
        f"""<tr style="background:{'#f8f9fa' if idx % 2 == 0 else '#fff'}">
              <td style="padding:6px 10px;border-bottom:1px solid #eee;color:#666">{idx}</td>
              <td style="padding:6px 10px;border-bottom:1px solid #eee;font-weight:bold">{s.symbol}</td>
              <td style="padding:6px 10px;border-bottom:1px solid #eee;text-align:right;color:#0f9d58;font-weight:bold">{s.delivery_percent:.1f}%</td>
              <td style="padding:6px 10px;border-bottom:1px solid #eee;text-align:right">&#8377;{s.close_price:.2f}</td>
              <td style="padding:6px 10px;border-bottom:1px solid #eee;text-align:right">{_format_qty(s.delivery_qty)}</td>
              <td style="padding:6px 10px;border-bottom:1px solid #eee;text-align:right">{_format_qty(s.traded_qty)}</td>
            </tr>"""
        for idx, s in enumerate(snapshot.stocks[:20], start=1)
    )
    return f"""
<p style="color:#666;margin-bottom:8px">Trade date: <strong>{snapshot.trade_date:%d %b %Y}</strong> &bull; Sorted by delivery % (highest first)</p>
<table style="width:100%;border-collapse:collapse;font-size:13px">
  <tr style="background:#e8f0fe;color:#174ea6">
    <th style="padding:7px 10px;text-align:left">#</th>
    <th style="padding:7px 10px;text-align:left">Symbol</th>
    <th style="padding:7px 10px;text-align:right">Delivery %</th>
    <th style="padding:7px 10px;text-align:right">Close</th>
    <th style="padding:7px 10px;text-align:right">Delivery Qty</th>
    <th style="padding:7px 10px;text-align:right">Traded Qty</th>
  </tr>
  {rows}
</table>"""


def build_sector_html(sector_stocks: list[TodayDeliveryStock]) -> str:
    if not sector_stocks:
        return '<p style="color:#666">No sector data available for today.</p>'

    sector_order: list[str] = []
    grouped: dict[str, dict[str, list[TodayDeliveryStock]]] = {}
    for s in sector_stocks:
        if s.sector not in grouped:
            sector_order.append(s.sector)
            grouped[s.sector] = {}
        if s.sub_sector not in grouped[s.sector]:
            grouped[s.sector][s.sub_sector] = []
        grouped[s.sector][s.sub_sector].append(s)

    parts: list[str] = []
    for sector in sector_order:
        inner_rows: list[str] = []
        for sub_sector, stocks in grouped[sector].items():
            inner_rows.append(
                f'<tr><td colspan="4" style="padding:4px 10px;background:#e8f0fe;'
                f'color:#174ea6;font-size:12px;font-weight:bold;'
                f'border-bottom:1px solid #c5d5f5">{sub_sector}</td></tr>'
            )
            for s in stocks:
                inner_rows.append(
                    f'<tr>'
                    f'<td style="padding:6px 10px;border-bottom:1px solid #eee;font-weight:bold">{s.symbol}</td>'
                    f'<td style="padding:6px 10px;border-bottom:1px solid #eee;text-align:right">&#8377;{s.close_price:.2f}</td>'
                    f'<td style="padding:6px 10px;border-bottom:1px solid #eee;text-align:right">'
                    f'<span style="color:{s.fund_color};font-weight:bold">{s.delivery_percent:.1f}%</span>'
                    f'<span style="color:{s.fund_color};font-size:11px"> {s.fund_label}</span></td>'
                    f'<td style="padding:6px 10px;border-bottom:1px solid #eee;text-align:right">'
                    f'<span style="color:{s.tech_color};font-weight:bold">{s.tech_arrow} {s.tech_label}</span>'
                    f'<span style="color:#888;font-size:11px"> ({s.technical_score:.0f})</span></td>'
                    f'</tr>'
                )
        parts.append(
            f'<div style="margin-bottom:16px">'
            f'<div style="background:#1a73e8;color:#fff;padding:6px 12px;border-radius:4px 4px 0 0;font-weight:bold;font-size:13px">{sector}</div>'
            f'<table style="width:100%;border-collapse:collapse;font-size:13px">'
            f'<tr style="background:#f1f3f4">'
            f'<th style="padding:6px 10px;text-align:left;color:#555;font-size:12px">Symbol</th>'
            f'<th style="padding:6px 10px;text-align:right;color:#555;font-size:12px">Close</th>'
            f'<th style="padding:6px 10px;text-align:right;color:#555;font-size:12px">Fundamental</th>'
            f'<th style="padding:6px 10px;text-align:right;color:#555;font-size:12px">Technical</th>'
            f'</tr>'
            f'{"".join(inner_rows)}'
            f'</table></div>'
        )
    return "\n".join(parts)


def send_email_report(
    items: list[NewsItem],
    insights: list[str],
    now: datetime,
    to_email: str,
    delivery_snapshot: TodayDeliverySnapshot | None = None,
    sector_stocks: list[TodayDeliveryStock] | None = None,
):
    if not to_email:
        return

    insight_rows = ''.join(f'<li>{i}</li>' for i in insights) if insights else '<li>No AI insights available.</li>'
    news_rows = ''.join(
        f'''<tr>
              <td style="padding:10px 14px;border-bottom:1px solid #eee">
                <a href="{item.link}" style="color:#1a73e8;font-weight:bold;text-decoration:none">{item.title}</a><br>
                <span style="color:#888;font-size:12px">{item.source}</span>
              </td>
            </tr>'''
        for item in items
    )
    delivery_html = build_delivery_html(delivery_snapshot)
    sector_html = build_sector_html(sector_stocks or [])

    html = f"""
<html><body style="font-family:Arial,sans-serif;color:#222;max-width:650px;margin:auto">
<h2 style="background:#0f9d58;color:#fff;padding:14px 20px;border-radius:6px;margin:0">
  Indian Stock Market Report - {now:%A, %d %B %Y}
</h2>

<h3 style="color:#0f9d58;margin-top:20px">Coming Week Sector Outlook</h3>
<ul style="line-height:1.8">{insight_rows}</ul>

<h3 style="color:#0f9d58;margin-top:20px">Today's Top 20 Delivery % Stocks (Highest → Lowest)</h3>
{delivery_html}

<h3 style="color:#0f9d58;margin-top:20px">Sector-wise Top 20 — Fundamental &amp; Technical</h3>
<p style="color:#666;font-size:12px;margin-bottom:10px">Ranked by combined delivery % + price position in day's range. Sub-sectors highlighted in blue.</p>
{sector_html}

<h3 style="color:#0f9d58;margin-top:20px">Indian Market Headlines</h3>
<table style="width:100%;border-collapse:collapse;font-size:14px">
  {news_rows}
</table>

<p style="margin-top:24px;color:#666;font-size:12px">
  Auto-generated by your Indian Stock Market AI Agent - {now:%Y-%m-%d %H:%M}
</p>
</body></html>
"""

    try:
        service = get_gmail_service()
        msg = MIMEMultipart('alternative')
        msg['Subject'] = f'Indian Stock Market Report - {now:%d %b %Y} - {len(items)} stories'
        msg['From'] = 'me'
        msg['To'] = to_email
        msg.attach(MIMEText(html, 'html'))
        raw = base64.urlsafe_b64encode(msg.as_bytes()).decode()
        send_gmail_message_with_retries(service, raw)
        print(f"Report emailed to {to_email}")
    except Exception as e:
        print(f"Email report failed: {e}")


def agent_run(config_path: str, publish: bool) -> None:
    print("Agent started...")

    config = load_config(config_path)
    items = fetch_stock_news(
        feeds=config["feeds"],
        max_items=int(config.get("max_items", 8)),
    )

    now = datetime.now()
    delivery_snapshot: TodayDeliverySnapshot | None = None
    if bool(config.get("delivery_enabled", True)):
        delivery_snapshot = fetch_today_delivery_top(
            top_n=int(config.get("delivery_top_n", 500)),
            min_traded_qty=int(config.get("delivery_min_traded_qty", 10000)),
        )

    insights: list[str] = []
    if bool(config.get("insights_enabled", True)):
        openai_key_env = config.get("openai_api_key_env", "GROQ_API_KEY")
        openai_key = load_openai_key(openai_key_env)
        insights = generate_ai_insights(
            items=items,
            api_key=openai_key,
            model=config.get("openai_model", "llama-3.3-70b-versatile"),
            max_points=int(config.get("insights_max_points", 4)),
            delivery_snapshot=delivery_snapshot,
        )

    post_text = build_daily_post(items, now, insights=insights, delivery_snapshot=delivery_snapshot)
    saved_path = save_to_file(post_text, output_dir=config.get("output_dir", "posts"), prefix="stock_news")

    if not saved_path:
        print("No post saved.")
        return

    # Send email report
    report_email = config.get("report_email", "") or os.getenv("REPORT_EMAIL", "")
    sector_stocks = build_sector_top(delivery_snapshot.stocks if delivery_snapshot else [], top_n=20)
    send_email_report(items, insights, now, report_email, delivery_snapshot=delivery_snapshot, sector_stocks=sector_stocks)

    if publish:
        webhook_env_name = config.get("webhook_url_env", "NEWS_WEBHOOK_URL")
        webhook_url = os.getenv(webhook_env_name, "")
        if not webhook_url:
            print(f"Publish skipped: set '{webhook_env_name}' env var to enable webhook.")
            return
        success = publish_to_webhook(webhook_url, post_text)
        print("Webhook publish: success" if success else "Webhook publish: failed")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Daily stock news agent")
    parser.add_argument("--config", default="agent_config.json", help="Path to config JSON")
    parser.add_argument("--publish", action="store_true", help="Post to webhook in addition to saving a file")
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    agent_run(config_path=args.config, publish=args.publish)

