import os
import time
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

DOMAINS_TO_TRASH = [
    "2coms.com",
    "aegisconsultants.in",
    "allegisglobalsolutions.com",
    "altezzasys.com",
    "am.dealsboat.com",
    "anandjikalyanjipedhi.org",
    "ansplacements.com",
    "applycup.com",
    "atlassystems.com",
    "avencoree.com",
    "avihr.in",
    "axelia.in",
    "beacontrustee.co.in",
    "beanhr.com",
    "berribot.com",
    "bitbybitsolutions.co.in",
    "blackwhite.in",
    "blenheimchalcot.com",
    "bluerose-tech.com",
    "cameoindia.com",
    "campaign1.nipponindia.email",
    "careerguideline.net",
    "careervisions.org",
    "celusion.com",
    "centuryiq.in",
    "choicetechlab.com",
    "cielhr.com",
    "codersbrain.com",
    "conceptshr.net",
    "consultbae.com",
    "coursera.org",
    "cpcareers.com",
    "cred.club",
    "crio.co.in",
    "crio.in",
    "cvlindia.in",
    "daksyam.com",
    "dare2compete.news",
    "datasciencemasterminds.com",
    "diamondpick.com",
    "digitalinclined.net",
    "e2einfoware.in",
    "eclerx.com",
    "elearnmarkets.com",
    "eloite.in",
    "em.flickonclick.com",
    "em.goconnectmail.com",
    "em.smctradeonline.com",
    "email.citiustech.com",
    "email.microsoft.com",
    "email2.microsoft.com",
    "emaila.1mg.com",
    "emailer.idfcfirst.bank.in",
    "emailer.idfcfirstbank.com",
    "emailer.pharmeasy.in",
    "emailers.idfcfirst.bank.in",
    "emailers.idfcfirstbank.com",
    "empowerhr.in",
    "enews.sodapdf.com",
    "enigmajobs.com",
    "enrichtalents.com",
    "etaashconsultants.com",
    "eteaminc.com",
    "etprime.com",
    "everexpanse.com",
    "excelityglobal.com",
    "experts.cvxinsights.com",
    "factorialsolutions.com",
    "faxoc.com",
    "finoux.com",
    "firstnaukri.com",
    "flocareer.com",
    "forward.net.in",
    "glassdoor.com",
    "globalhunt.in",
    "globecapital.com",
    "globeclients.com",
    "goldmedalindia.com",
    "googlemail.com",
    "green-clover.in",
    "hackerrankforwork.com",
    "hcapital.in",
    "headhuntershr.com",
    "hgsbs.com",
    "hiregenics.com",
    "hirepro.in",
    "hiring.shine.com",
    "hirist.tech",
    "hiyamee.com",
    "hnssolution.in",
    "hopesforever.com",
    "host.discountwalas.com",
    "ibridgetechsoft.com",
    "idealake.com",
    "impeccablehr.com",
    "indeed.com",
    "indiamailers.com",
    "infinitygrowth.live",
    "initialinfinity.com",
    "innovasolutions.com",
    "integratedregistry.in",
    "interviewkickstart.com",
    "inubesolutions.com",
    "iqzsystems.com",
    "jmproapp.com",
    "jobs.shine.com",
    "jobsalert.shine.com",
    "jobsearch.shine.com",
    "jobseekers.shine.com",
    "joulestowatts.com",
    "kasmodigital.com",
    "kennit.co.in",
    "konnectinsights.com",
    "kratin.co.in",
    "ktekresourcing.com",
    "litsaservices.com",
    "lnsinfotech.com",
    "mail.beehiiv.com",
    "mail.instagram.com",
    "mail.perplexity.ai",
    "mail.tatamf.in",
    "mailer.emailsinbox.com",
    "mailer.eurekaforbeslimited.co.in",
    "mailer.jio.com",
    "mailer.moneycontrol.com",
    "mailer.officenewz.com",
    "maveric-systems.com",
    "mediwheel.in",
    "mg.sg.graphy.com",
    "mindpooltech.in",
    "mintinternational.com",
    "mitsit.net",
    "mkttech.in",
    "mnrsolutions.in",
    "money.livemint.com",
    "monocept.com",
    "mounttalent.com",
    "mouthshut.com",
    "msrtcors.com",
    "mundrisoft.com",
    "myanatomy.in",
    "mybrandbook.co.in",
    "naukrirms.com",
    "navasoftware.com",
    "neoquant.com",
    "neweraindia.com",
    "newsletters.analyticsvidhya.com",
    "nityo.com",
    "nl.flickonclick.com",
    "nmplacement.com",
    "nodnetworks.com",
    "northgateps.com",
    "notification.circle.so",
    "notifications-economictimes.com",
    "noveltalentsolutions.com",
    "olaelectric.com",
    "olibr.com",
    "orchasp.com",
    "osourceglobal.com",
    "pegasusinfocorp.com",
    "people-prime.com",
    "photokhazana.com",
    "pmam.com",
    "pnm.nobroker.in",
    "primesoft.net",
    "prismhrc.in",
    "prometheusconsulting.in",
    "protalentconnect.in",
    "quant.in",
    "quantitas.in",
    "rarefindindia.com",
    "rathi.com",
    "responseinformatics.com",
    "rightbrain.co.in",
    "ripplehire.com",
    "rsquare-solutions.com",
    "saivasystem.com",
    "samhrpo.com",
    "sapphiremanpower.com",
    "scaler.com",
    "sensehr.com",
    "sgsconsulting.com",
    "simplilearn.net",
    "simplilearnmailer.com",
    "skillkart.co",
    "smartruntech.com",
    "smt.plusoasis.com",
    "sphereinfo.in",
    "springhr.com",
    "spruceinfotech.com",
    "stratosphere.co.in",
    "suntechnologies.com",
    "survik.com",
    "sysaccord.com",
    "talent500.co",
    "talenti.biz",
    "talenttitanletters.com",
    "tanishasystems.com",
    "tdsmail.taxosmart.in",
    "techopp.in",
    "techopportunity.in",
    "techslash.com",
    "tekishub.com",
    "teksystems.com",
    "tgt.net.in",
    "therecruitx.com",
    "timesjobs.com",
    "ui.dev",
    "uniquehire.co.in",
    "uplers.com",
    "uplers.network",
    "uto.in",
    "valuelabs.com",
    "varite.com",
    "vdvm16.logix.local",
    "voyagerpartners.com",
    "vp.pl",
    "wayfarertrip.com",
    "weareams.com",
    "winsoftech.com",
    "xaltius.tech",
    "xobin.com",
    "zintro.com",
    "2softsolutions.com",
    "agreeya.com",
    "akgroup.co.in",
    "antal.com",
    "apexgroup.com",
    "appmix.com",
    "bcone.com",
    "bolt-on.in",
    "brainvire.com",
    "careedge.in",
    "derivativetradingacademy.com",
    "economictimesnews.com",
    "eexpedise.com",
    "eicoretech.com",
    "envecon.com",
    "eurosmile.in",
    "harjai.com",
    "hr-central.in",
    "ignitivesearch.com",
    "infrasofttech.com",
    "infyshine.com",
    "insyncanalytics.com",
    "irishigherground.com",
    "irisindia.net",
    "itsourceindia.com",
    "jaro.in",
    "kggroup.com",
    "manpowermining.com",
    "matrixbsindia.com",
    "mitsit.in",
    "mumbairozgaar.com",
    "nextprospects.com",
    "nimapinfotech.com",
    "oshoventures.com",
    "powerweave.com",
    "pramahikvision.com",
    "realtekconsulting.net",
    "rexus-group.com",
    "skillventory.com",
    "sts.in",
    "sunraycorp.com",
    "systems-plus.com",
    "taggd.in",
    "tridatindia.com",
    "vacancies.shine.com",
    "vertextechsol.com",
    "vnnogile.com",
    "wisebee.in",
    "zarca.com",
    "citiustech.com",
    "cloverinfotech.com",
    "lntinfotech.com",
    "mail.interviewkickstart.com",
    "neosofttech.com",
    "pmamit.com",
    "rebit.org.in",
    "tekspire.in",
    "thinkpeople.in",
    "xebia.com",
]

creds = Credentials(
    token=None,
    refresh_token=os.environ['GOOGLE_REFRESH_TOKEN'],
    token_uri='https://oauth2.googleapis.com/token',
    client_id=os.environ['GOOGLE_CLIENT_ID'],
    client_secret=os.environ['GOOGLE_CLIENT_SECRET'],
    scopes=['https://www.googleapis.com/auth/gmail.modify'],
)
creds.refresh(Request())
service = build('gmail', 'v1', credentials=creds)

total_trashed = 0

for domain in DOMAINS_TO_TRASH:
    msg_ids = []
    page_token = None
    while True:
        kwargs = {'userId': 'me', 'q': f'in:inbox from:@{domain}', 'maxResults': 500}
        if page_token:
            kwargs['pageToken'] = page_token
        result = service.users().messages().list(**kwargs).execute()
        msg_ids.extend([m['id'] for m in result.get('messages', [])])
        page_token = result.get('nextPageToken')
        if not page_token:
            break

    if not msg_ids:
        continue

    # Batch trash in groups of 100
    for i in range(0, len(msg_ids), 100):
        batch = service.new_batch_http_request()
        for msg_id in msg_ids[i:i+100]:
            batch.add(service.users().messages().trash(userId='me', id=msg_id))
        try:
            batch.execute()
        except HttpError as e:
            print(f'  Batch error for {domain}: {e}', flush=True)
            time.sleep(2)

    total_trashed += len(msg_ids)
    print(f'[TRASHED {len(msg_ids):4d}] {domain}', flush=True)

print(f'\nDone. Total trashed: {total_trashed}', flush=True)
